---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: smartrelay

# the base path to install to. You should not need to change this.
install_root: /srv

project_path: "{{ install_root }}/django/{{ project_name }}/"

# the python module path to your project's wsgi file. E.g. for a directory
# layout like this (assuming `django_hello` is the project_name and top level
# directory name):
# django_hello
# ├── hello
# │   ├── apps
# │   ├── __init__.py
# │   ├── settings.py
# │   ├── urls.py
# │   └── wsgi.py
# ├── manage.py
# └── requirements.txt
# the correct wsgi_module value would be `hello.wsgi`
wsgi_module: smartrelay.wsgi

virtual_env: "{{ install_root }}/{{ project_name }}/venv"

# any directories that need to be added to the PYTHONPATH.
pythonpath: "{{ virtual_env }}/bin/python"

# the git repository URL for the project
project_repo: git@github.com:juancrescente/smartrelay.git
    
# a private key that has access to the repository URL
ssh_private_key: ~/.ssh/id_rsa

# The value of your django project's STATIC_ROOT settings.
# This will be the directory that django's `collectstatic` management command
# copies static files to, and it must be an absolute path. The default value 
# here assumes that STATIC_ROOT is set in your settings.py like so:
# STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, 'static'))
static_root: "{{ install_root }}/{{ project_name }}/static"

# the dns name or names (space separated) for your server
server_name: 164.90.178.147

# apt packages, you should not need to change this unless you have packages
# listed in your requirements.txt that depend on system packages.
system_packages:
  - git
  - nginx
  - gunicorn
  - python-pip
  - python-dev
  - virtualenv

# vim:ft=ansible:
